In [1]:
import numpy as np
import pandas as pd

In [22]:
def fetch_financial_data(company='AMZN'):
    import pandas_datareader.data as web
    return web.DataReader(name=company, data_source='stooq')


df = fetch_financial_data()

In [23]:
df = df.sort_index()

In [25]:
df.to_csv('AMZN.csv')

In [28]:
df_nov = df[(df.index.month == 11) & (df.index.year==2019)]

In [30]:
df_nov.to_csv("AMZN_nov.csv")

In [40]:
new_df = pd.read_csv('AMZN_nov.csv', index_col=0)

In [41]:
new_df

               Open     High      Low    Close    Volume
Date
2019-11-01  89.4005  89.8725  89.2605  89.5720  55807080
2019-11-04  90.0505  90.7530  90.0505  90.2330  55438440
2019-11-05  90.4580  90.5125  89.7000  90.0855  37710860
2019-11-06  90.0500  90.1250  89.4290  89.7885  40595660
2019-11-07  90.1880  90.2950  89.1740  89.4100  53021720
2019-11-08  89.3945  89.4940  88.7020  89.2940  42523960
2019-11-11  88.9000  89.0000  88.3565  88.5825  38956200
2019-11-12  88.7330  89.3110  88.5955  88.9000  40778500
2019-11-13  88.6695  88.7500  87.3660  87.6555  58537840
2019-11-14  87.5715  88.3295  87.4780  87.7300  45388340
2019-11-15  88.0025  88.0840  86.6430  86.9745  78622820
2019-11-18  86.9150  87.6850  86.1355  87.6265  56838140
2019-11-19  87.8495  88.0340  87.1515  87.6395  45490700
2019-11-20  87.4570  88.1260  86.7060  87.2765  55875180
2019-11-21  87.1500  87.3435  86.5180  86.7355  53258760
2019-11-22  86.9510  87.3215  86.5500  87.2860  49581620
2019-11-25  87.6625  88.8710  87.6620  88.6920  69789340
2019-11-26  88.9960  89.8515  88.9175  89.8470  63808560
2019-11-27  90.0500  91.2250  89.8655  90.9255  60467100
2019-11-29  90.8890  91.2345  90.0395  90.0400  38468800